# DEPLOYMENT
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment
  labels:
    app: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - name: mongo
        image: mongo:6.0    # search from hub.docker.com to find specific image
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongo-secrets
              key: mongo-user
        env:
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef: # get the password from secret file
              name: mongo-secrets
              key: mongo-password

--- # end deployment yaml files 


# Service
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  selector:
    app: mongo # how i know it is mongo     got to line number 10 to 12 here selector are going to help
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017   # mongo port
