apiVersion: v1
kind: Secret 
metadata:
  name: mongo-secrets
  
type: Opaque
data:
  mongo-user: bW9uZ28tdXNlcg==  # password should encode before applying it here
  mongo-password: bW9uZ28tcGFzc3dvcmQ=