# DEPLOYMENT
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app-deployment
  labels:
    app: web-app
spec:
  replicas: 2   # depends on you if more number of replicas is present it balances load 
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
      - name: mongo-express
        image: mongo-express:latest    # search from hub.docker.com to find specific image
        ports:
        - containerPort: 8081
        env:
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME 
          valueFrom:
            secretKeyRef:
              name: mongo-secrets
              key: mongo-user
        env:
        - name: ME_CONFIG_MONGODB_ADMINPASSWORD 
          valueFrom:
            secretKeyRef: # get the password from secret file
              name: mongo-secrets
              key: mongo-password
        env:
        - name: ME_CONFIG_MONGODB_SERVER        
          valueFrom:
            configMapKeyRef: # get the password from secret file
              name: mongo-config
              key: mongo-password

--- # end deployment yaml files 


# Service
apiVersion: v1
kind: Service
metadata:
  name: web-app-service
spec:
  type: NodePort
  selector:
    app: web-app # how i know it is mongo     got to line number 10 to 12 here selector are going to help
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081   # mongo port
      nodePort: 30007
